package com.demo.models;
// Generated Apr 1, 2022, 12:33:46 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "demo_hibernate2")
public class Account implements java.io.Serializable {

	private String username;
	private String password;
	private String fullName;
	
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date birthday;
	private String gender;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Account() {
	}

	public Account(String username, String password, String fullName, Date birthday, String gender) {
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.birthday = birthday;
		this.gender = gender;
	}

	public Account(String username, String password, String fullName, Date birthday, String gender,
			Set<Orders> orderses) {
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.birthday = birthday;
		this.gender = gender;
		this.orderses = orderses;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 250)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "full_name", nullable = false, length = 250)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", nullable = false, length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "gender", nullable = false, length = 20)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
