package com.demo.models;
// Generated Apr 1, 2022, 12:33:46 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ordersdetail generated by hbm2java
 */
@Entity
@Table(name = "ordersdetail", catalog = "demo_hibernate2")
public class Ordersdetail implements java.io.Serializable {

	private OrdersdetailId id;
	private Orders orders;
	private Product product;
	private double price;
	private int quantity;

	public Ordersdetail() {
	}

	public Ordersdetail(OrdersdetailId id, Orders orders, Product product, double price, int quantity) {
		this.id = id;
		this.orders = orders;
		this.product = product;
		this.price = price;
		this.quantity = quantity;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ordersid", column = @Column(name = "ordersid", nullable = false)),
			@AttributeOverride(name = "productid", column = @Column(name = "productid", nullable = false)) })
	public OrdersdetailId getId() {
		return this.id;
	}

	public void setId(OrdersdetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ordersid", nullable = false, insertable = false, updatable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productid", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}












//<table id="example1" class="table table-bordered table-striped">
//<thead>
//<tr>
//		<th>ID</th>
//		<th>Order ID</th>
//		<th>Order date</th>
//		<th>Product name</th>								
//		<th>Customer name</th>
//		<th>Price</th>
//		<th>Quantity</th>
//		<th>Sub total</th>
//</tr>
//</thead>
//<tbody>
//<c:forEach var="order" items="${orders }" varStatus="i">
//<tr>
//	<td>${i.index + 1 }</td>
//	<td>${order.orders.id }</td>
//	<td>${order.orders.created }</td>
//	<td>${order.product.name }</td>
//	
//	<td>${order.orders.account.fullName }</td>
//	<td>${order.price }</td>
//	<td>${order.quantity }</td>
//	<td>${order.quantity * order.price }</td>
//</tr>
//</c:forEach>
//</tbody>
//<tfoot>
//<tr>
//		<th>ID</th>
//		<th>Product name</th>			
//		<th>Order date</th>
//		<th>Price</th>
//		<th>Quantity</th>
//</tr>
//</tfoot>
//</table>
